device: "cuda"
experiment_name: test1
seed: 0

gymnasium:
    env_id: ALE/Boxing-v5
    # env_id: ALE/Breakout-v5
    channel_first: True
    discrete: True
    resize_obs: True
    new_obs_size: [64, 64]
    norm_obs: True

tensorboard:
    enable: False
    log_dir: "./runs/"
    log_frequency: 1  # Log every 1000 steps

wandb:
    enable: False
    project: "dreamer"
    entity: "phdminh01"
    log_frequency: 1

video_recording:
    enable: True
    record_frequency: 10  #episodes
    save_path: "./runs/"

main:
    total_iter: 2000
    collect_iter: 100
    data_interact_ep: 1
    # data_init_ep: 1
    data_init_ep: 5
    horizon: 10
    batch_size: 50
    seq_len: 50
    eval_eps: 3
    eval_freq: 5

    kl_divergence_scale : 1
    free_nats : 3
    discount : 0.99
    lambda_ : 0.95
    
    use_continue_flag : True
    actor_lr : 8.0e-5
    critic_lr : 8.0e-5
    dyna_model_lr : 6.0e-4
    grad_norm_type : 2
    clip_grad : 100
    
    hidden_units: 400
    deterministic_size : 600
    stochastic_size : 600
    embedded_obs_size : 1024
    buffer_capacity : 500000

    epsilon_start: 0.4
    epsilon_end: 0.1
    eps_decay_steps: 200000

    mean_noise: 0
    std_noise: 0.3